### ISSUE TITLE
Unable to require shard

### ISSUE THREAD

**Issue by nfpiche** [ysbaddaden/selenium-webdriver-crystal#2]
Hello,

Looking to utilize this shard for a project, but I am unable to require the shard into my project.

This is my shard.yml, it seems to install the dependency correctly

```
dependencies:
  selenium-webdriver:
    github: ysbaddaden/selenium-webdriver-crystal
    branch: master
```

But when I try to run the example from the README in my project I receive the following error
```
while requiring "selenium": can't find file 'selenium' relative to '/Users/npiche/asdf/src'
```
